config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :vulns
  
  get "home/features"
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :vulns
end

app/models/vuln.rb
class Vuln < ApplicationRecord

    #sets that vulns belong to user
    belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def features
  end
end

app/controllers/vulns_controller.rb
class VulnsController < ApplicationController
  before_action :set_vuln, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except:[:index, :show]
  #only allows certain functions when correct user
  before_action :correct_user,only:[:edit, :update, :destroy]

  # GET /vulns or /vulns.json
  def index
    @vulns = Vuln.all
  end

  # GET /vulns/1 or /vulns/1.json
  def show
  end

  # GET /vulns/new
  def new
    #@vuln = Vuln.new
    @vuln = current_user.vulns.build
  end

  # GET /vulns/1/edit
  def edit
  end

  # POST /vulns or /vulns.json
  def create
    #@vuln = Vuln.new(vuln_params)
    @vuln = current_user.vulns.build(vuln_params)
    respond_to do |format|
      if @vuln.save
        format.html { redirect_to vuln_url(@vuln), notice: "Vuln was successfully created." }
        format.json { render :show, status: :created, location: @vuln }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @vuln.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vulns/1 or /vulns/1.json
  def update
    respond_to do |format|
      if @vuln.update(vuln_params)
        format.html { redirect_to vuln_url(@vuln), notice: "Vuln was successfully updated." }
        format.json { render :show, status: :ok, location: @vuln }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @vuln.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vulns/1 or /vulns/1.json
  def destroy
    @vuln.destroy

    respond_to do |format|
      format.html { redirect_to vulns_url, notice: "Vuln was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # searches up if correct user by comparing current user to devise primary key user
  def correct_user
    @vuln = current_user.vulns.find_by(id: params[:id])
    redirect_to vulns_path,notice: "Please Authorise to Edit Vulnerability Details" if @vuln.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vuln
      @vuln = Vuln.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def vuln_params
      params.require(:vuln).permit(:vuln_name, :vuln_type, :cve, :discovered, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/vulns_helper.rb
module VulnsHelper
end

app/views/home/_head.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to 'Sean Security Solutions',root_path,class:"navbar-brand" %>
  
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        
        

        <li class="nav-item">
          <%= link_to 'Vulnerability List', vulns_path,class:"nav-link"%>
        </li>

        

        <%if user_signed_in?%>
          <li class="nav-item">
          <%= link_to 'Add a New Vulnerability ', new_vuln_path,class:"nav-link"%>
        </li>



          <li class="nav-item">
          <%= link_to 'Log Out ', destroy_user_session_path,class:"nav-link"%>
        </li>

        <li class="nav-item">
          <%= link_to 'Edit Profile ', edit_user_registration_path,class:"nav-link"%>
        </li>

        <%else %>
        <li class="nav-item">
          <%= link_to 'Sign Up ', new_user_registration_path,class:"nav-link"%>
        </li>

        <li class="nav-item">
          <%= link_to 'Sign In ', new_user_session_path,class:"nav-link"%>
        </li>

        <%end%>
        
        
      </ul>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<p>hello this is our security solutions page pleas add you client details</p>

app/views/layouts/_alerts.html.erb
 <div class="alert alert-success d-flex align-items-center" role="alert">
  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img" aria-label="Warning:">
    <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
  </svg>
  <div>
    <%=notice%>
  </div>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Security Solutions</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>
  <body>

    <%= render 'home/head' %>
    <div class='container'>
      <%if notice%>
        <%=render 'layouts/alerts'%>
      <%end%>
      <br/>
    <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </body>
</html>

app/views/vulns/_form.html.erb
<%= form_with(model: vuln) do |form| %>
  <% if vuln.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(vuln.errors.count, "error") %> prohibited this vuln from being saved:</h2>

      <ul>
        <% vuln.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <div class="d-grid gap-2">
    <%= form.label :Vulnerability_Name, style: "display: block" %>
    <%= form.text_field :vuln_name,class:"form-control" %>
  </div>

  <div class="d-grid gap-2">
    <%= form.label :Vulnerability_Type, style: "display: block" %>
    <%= form.text_field :vuln_type,class:"form-control" %>
  </div>

  <div class="d-grid gap-2">
    <%= form.label :CVE, style: "display: block" %>
    <%= form.text_field :cve,class:"form-control" %>
  </div>

  <div class="d-grid gap-2">
    <%= form.label :discovered, style: "display: center" %>
    <%= form.date_field :discovered,class:"form-control" %>
  </div>

  <div class="d-grid gap-2">
    <%= form.number_field :user_id,id: :vuln_user_id,class:"form-control",value:current_user.id,type: :hidden%>
  </div>
  

<br>

  <div class="d-grid gap-2">
    <%= form.submit class:'btn btn-outline-primary'%>
  </div>
<% end %>

app/views/vulns/_vuln.html.erb
<div id="<%= dom_id vuln %>">
  <p>
    <strong>Vuln name:</strong>
    <%= vuln.vuln_name %>
  </p>

  <p>
    <strong>Vuln type:</strong>
    <%= vuln.vuln_type %>
  </p>

  <p>
    <strong>Cve:</strong>
    <%= vuln.cve %>
  </p>

  <p>
    <strong>Discovered:</strong>
    <%= vuln.discovered %>
  </p>

</div>

app/views/vulns/edit.html.erb
<h1>Editing vuln</h1>

<%= render "form", vuln: @vuln %>

<br>

<div class="btn-group  gap-2 col-12 mx-auto">
  <%= link_to "Show this vuln", @vuln, class:'btn btn-outline-primary'%> 
  <%= link_to "Back to vulns", vulns_path, class:'btn btn-outline-secondary'%>
  
</div>

app/views/vulns/index.html.erb
<h1>Vulnerability List</h1>
<%#sets up table%>
<table id="vulns"class="table table-bordered">

  <thead>
    <tr>
      <th scope="col">Vulnerability Name</th>
      <th scope="col">Vulnerability Type</th>
      <th scope="col">Common Vulnerabilities and Exposures</th>
      <th scope="col">Date Vulnerability was discovered</th>
      <th scope="col">User Id</th>
      <th scope="col">Extra Details</th>
    </tr>
  </thead>
  <tbody>
    <%#loops through for the amount of vulns but only if the vuln user matches the current user%>
  <% @vulns.each do |vuln| %>
    <% if vuln.user== current_user%>
  <tr>
        <td><%= vuln.vuln_name %></td>
        <td><%= vuln.vuln_type %></td>
        <td><%= vuln.cve %></td>
        <td><%= vuln.discovered %></td>
        <td><%= vuln.user_id %></td>
        <td><%= link_to "Show Vulnerability", vuln,class:'btn btn-primary' %></td>
  </tr> 
    <%end%>
  </tbody>     
    
      
    
  <% end %>
</table>





<%= link_to "Add a New Vulnerability", new_vuln_path,class:'btn btn-primary' %>

app/views/vulns/new.html.erb
<h1>Enter Details For your Vulnerability</h1>

<%= render "form", vuln: @vuln %>

<br>

<div class="d-grid gap-2">
  <%= link_to "Back to vulns", vulns_path, class:"btn btn-outline-secondary"%>
</div>

app/views/vulns/show.html.erb
<div class="card">
    <div class="card-body">
<%= render @vuln %>
    </div>
</div>

<div class="btn-group gap-2 col-12 mx-auto">
  <%= link_to "Edit this vuln", edit_vuln_path(@vuln) , class:"btn btn-outline-primary" %>
  <%= button_to "Destroy this vuln", @vuln, method: :delete, class:"btn btn-outline-danger" %>
  <%= link_to "Back to vulns", vulns_path , class:"btn btn-outline-secondary" %>
  
</div>